/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PortalJogosRouteImport } from './routes/portal.jogos'
import { Route as ApiPublicSyncResultsRouteImport } from './routes/api/public/sync-results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalJogosRoute = PortalJogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => PortalRoute,
} as any)
const ApiPublicSyncResultsRoute = ApiPublicSyncResultsRouteImport.update({
  id: '/api/public/sync-results',
  path: '/api/public/sync-results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/jogos': typeof PortalJogosRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/jogos': typeof PortalJogosRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/jogos': typeof PortalJogosRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/portal' | '/portal/jogos' | '/api/public/sync-results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/portal' | '/portal/jogos' | '/api/public/sync-results'
  id:
    '__root__' | '/' | '/portal' | '/portal/jogos' | '/api/public/sync-results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  ApiPublicSyncResultsRoute: typeof ApiPublicSyncResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/jogos': {
      id: '/portal/jogos'
      path: '/jogos'
      fullPath: '/portal/jogos'
      preLoaderRoute: typeof PortalJogosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/public/sync-results': {
      id: '/api/public/sync-results'
      path: '/api/public/sync-results'
      fullPath: '/api/public/sync-results'
      preLoaderRoute: typeof ApiPublicSyncResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalJogosRoute: typeof PortalJogosRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalJogosRoute: PortalJogosRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  ApiPublicSyncResultsRoute: ApiPublicSyncResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
