/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCruzDoDiaRouteImport } from './routes/_authenticated/cruz-do-dia'
import { Route as AuthenticatedEstatisticasRouteImport } from './routes/_authenticated/estatisticas'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedRobotStatusRouteImport } from './routes/_authenticated/robot-status'
import { Route as AuthenticatedPortalJogosRouteImport } from './routes/_authenticated/portal.jogos'
import { Route as ApiPublicSyncResultsRouteImport } from './routes/api/public/sync-results'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCruzDoDiaRoute = AuthenticatedCruzDoDiaRouteImport.update({
  id: '/_authenticated/cruz-do-dia',
  path: '/cruz-do-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstatisticasRoute =
  AuthenticatedEstatisticasRouteImport.update({
    id: '/_authenticated/estatisticas',
    path: '/estatisticas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/_authenticated/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/_authenticated/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRobotStatusRoute =
  AuthenticatedRobotStatusRouteImport.update({
    id: '/_authenticated/robot-status',
    path: '/robot-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalJogosRoute =
  AuthenticatedPortalJogosRouteImport.update({
    id: '/jogos',
    path: '/jogos',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const ApiPublicSyncResultsRoute = ApiPublicSyncResultsRouteImport.update({
  id: '/api/public/sync-results',
  path: '/api/public/sync-results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/cruz-do-dia': typeof AuthenticatedCruzDoDiaRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/robot-status': typeof AuthenticatedRobotStatusRoute
  '/': typeof AuthenticatedIndexRoute
  '/portal/jogos': typeof AuthenticatedPortalJogosRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
}
export interface FileRoutesByTo {
  '/cruz-do-dia': typeof AuthenticatedCruzDoDiaRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/robot-status': typeof AuthenticatedRobotStatusRoute
  '/': typeof AuthenticatedIndexRoute
  '/portal/jogos': typeof AuthenticatedPortalJogosRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/cruz-do-dia': typeof AuthenticatedCruzDoDiaRoute
  '/_authenticated/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/robot-status': typeof AuthenticatedRobotStatusRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/portal/jogos': typeof AuthenticatedPortalJogosRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cruz-do-dia'
    | '/estatisticas'
    | '/historico'
    | '/portal'
    | '/robot-status'
    | '/'
    | '/portal/jogos'
    | '/api/public/sync-results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cruz-do-dia'
    | '/estatisticas'
    | '/historico'
    | '/portal'
    | '/robot-status'
    | '/'
    | '/portal/jogos'
    | '/api/public/sync-results'
  id:
    | '__root__'
    | '/_authenticated/cruz-do-dia'
    | '/_authenticated/estatisticas'
    | '/_authenticated/historico'
    | '/_authenticated/portal'
    | '/_authenticated/robot-status'
    | '/_authenticated/'
    | '/_authenticated/portal/jogos'
    | '/api/public/sync-results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedCruzDoDiaRoute: typeof AuthenticatedCruzDoDiaRoute
  AuthenticatedEstatisticasRoute: typeof AuthenticatedEstatisticasRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedRobotStatusRoute: typeof AuthenticatedRobotStatusRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  ApiPublicSyncResultsRoute: typeof ApiPublicSyncResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cruz-do-dia': {
      id: '/_authenticated/cruz-do-dia'
      path: '/cruz-do-dia'
      fullPath: '/cruz-do-dia'
      preLoaderRoute: typeof AuthenticatedCruzDoDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estatisticas': {
      id: '/_authenticated/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof AuthenticatedEstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/robot-status': {
      id: '/_authenticated/robot-status'
      path: '/robot-status'
      fullPath: '/robot-status'
      preLoaderRoute: typeof AuthenticatedRobotStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/jogos': {
      id: '/_authenticated/portal/jogos'
      path: '/jogos'
      fullPath: '/portal/jogos'
      preLoaderRoute: typeof AuthenticatedPortalJogosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/api/public/sync-results': {
      id: '/api/public/sync-results'
      path: '/api/public/sync-results'
      fullPath: '/api/public/sync-results'
      preLoaderRoute: typeof ApiPublicSyncResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalJogosRoute: typeof AuthenticatedPortalJogosRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalJogosRoute: AuthenticatedPortalJogosRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedCruzDoDiaRoute: AuthenticatedCruzDoDiaRoute,
  AuthenticatedEstatisticasRoute: AuthenticatedEstatisticasRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedRobotStatusRoute: AuthenticatedRobotStatusRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  ApiPublicSyncResultsRoute: ApiPublicSyncResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
