/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PendenteRouteImport } from './routes/pendente'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnalisesRouteImport } from './routes/_authenticated/analises'
import { Route as AuthenticatedArquivoRouteImport } from './routes/_authenticated/arquivo'
import { Route as AuthenticatedCadastrarRouteImport } from './routes/_authenticated/cadastrar'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCruzDoDiaRouteImport } from './routes/_authenticated/cruz-do-dia'
import { Route as AuthenticatedEstatisticasRouteImport } from './routes/_authenticated/estatisticas'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedPalpiteRouteImport } from './routes/_authenticated/palpite'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedRobotStatusRouteImport } from './routes/_authenticated/robot-status'
import { Route as AuthenticatedPortalJogosRouteImport } from './routes/_authenticated/portal.jogos'
import { Route as ApiPublicSyncResultsRouteImport } from './routes/api/public/sync-results'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenteRoute = PendenteRouteImport.update({
  id: '/pendente',
  path: '/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalisesRoute = AuthenticatedAnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArquivoRoute = AuthenticatedArquivoRouteImport.update({
  id: '/arquivo',
  path: '/arquivo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrarRoute = AuthenticatedCadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCruzDoDiaRoute = AuthenticatedCruzDoDiaRouteImport.update({
  id: '/cruz-do-dia',
  path: '/cruz-do-dia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstatisticasRoute =
  AuthenticatedEstatisticasRouteImport.update({
    id: '/estatisticas',
    path: '/estatisticas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPalpiteRoute = AuthenticatedPalpiteRouteImport.update({
  id: '/palpite',
  path: '/palpite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRobotStatusRoute =
  AuthenticatedRobotStatusRouteImport.update({
    id: '/robot-status',
    path: '/robot-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalJogosRoute =
  AuthenticatedPortalJogosRouteImport.update({
    id: '/jogos',
    path: '/jogos',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const ApiPublicSyncResultsRoute = ApiPublicSyncResultsRouteImport.update({
  id: '/api/public/sync-results',
  path: '/api/public/sync-results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/pendente': typeof PendenteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analises': typeof AuthenticatedAnalisesRoute
  '/arquivo': typeof AuthenticatedArquivoRoute
  '/cadastrar': typeof AuthenticatedCadastrarRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cruz-do-dia': typeof AuthenticatedCruzDoDiaRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/palpite': typeof AuthenticatedPalpiteRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/robot-status': typeof AuthenticatedRobotStatusRoute
  '/portal/jogos': typeof AuthenticatedPortalJogosRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/pendente': typeof PendenteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analises': typeof AuthenticatedAnalisesRoute
  '/arquivo': typeof AuthenticatedArquivoRoute
  '/cadastrar': typeof AuthenticatedCadastrarRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cruz-do-dia': typeof AuthenticatedCruzDoDiaRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/palpite': typeof AuthenticatedPalpiteRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/robot-status': typeof AuthenticatedRobotStatusRoute
  '/': typeof AuthenticatedIndexRoute
  '/portal/jogos': typeof AuthenticatedPortalJogosRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pendente': typeof PendenteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analises': typeof AuthenticatedAnalisesRoute
  '/_authenticated/arquivo': typeof AuthenticatedArquivoRoute
  '/_authenticated/cadastrar': typeof AuthenticatedCadastrarRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/cruz-do-dia': typeof AuthenticatedCruzDoDiaRoute
  '/_authenticated/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/palpite': typeof AuthenticatedPalpiteRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/robot-status': typeof AuthenticatedRobotStatusRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/portal/jogos': typeof AuthenticatedPortalJogosRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pendente'
    | '/reset-password'
    | '/admin'
    | '/analises'
    | '/arquivo'
    | '/cadastrar'
    | '/calendario'
    | '/configuracoes'
    | '/cruz-do-dia'
    | '/estatisticas'
    | '/historico'
    | '/palpite'
    | '/perfil'
    | '/portal'
    | '/robot-status'
    | '/portal/jogos'
    | '/api/public/sync-results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/pendente'
    | '/reset-password'
    | '/admin'
    | '/analises'
    | '/arquivo'
    | '/cadastrar'
    | '/calendario'
    | '/configuracoes'
    | '/cruz-do-dia'
    | '/estatisticas'
    | '/historico'
    | '/palpite'
    | '/perfil'
    | '/portal'
    | '/robot-status'
    | '/'
    | '/portal/jogos'
    | '/api/public/sync-results'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/pendente'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/analises'
    | '/_authenticated/arquivo'
    | '/_authenticated/cadastrar'
    | '/_authenticated/calendario'
    | '/_authenticated/configuracoes'
    | '/_authenticated/cruz-do-dia'
    | '/_authenticated/estatisticas'
    | '/_authenticated/historico'
    | '/_authenticated/palpite'
    | '/_authenticated/perfil'
    | '/_authenticated/portal'
    | '/_authenticated/robot-status'
    | '/_authenticated/'
    | '/_authenticated/portal/jogos'
    | '/api/public/sync-results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendenteRoute: typeof PendenteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicSyncResultsRoute: typeof ApiPublicSyncResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendente': {
      id: '/pendente'
      path: '/pendente'
      fullPath: '/pendente'
      preLoaderRoute: typeof PendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analises': {
      id: '/_authenticated/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AuthenticatedAnalisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arquivo': {
      id: '/_authenticated/arquivo'
      path: '/arquivo'
      fullPath: '/arquivo'
      preLoaderRoute: typeof AuthenticatedArquivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastrar': {
      id: '/_authenticated/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof AuthenticatedCadastrarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cruz-do-dia': {
      id: '/_authenticated/cruz-do-dia'
      path: '/cruz-do-dia'
      fullPath: '/cruz-do-dia'
      preLoaderRoute: typeof AuthenticatedCruzDoDiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estatisticas': {
      id: '/_authenticated/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof AuthenticatedEstatisticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/palpite': {
      id: '/_authenticated/palpite'
      path: '/palpite'
      fullPath: '/palpite'
      preLoaderRoute: typeof AuthenticatedPalpiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/robot-status': {
      id: '/_authenticated/robot-status'
      path: '/robot-status'
      fullPath: '/robot-status'
      preLoaderRoute: typeof AuthenticatedRobotStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/jogos': {
      id: '/_authenticated/portal/jogos'
      path: '/jogos'
      fullPath: '/portal/jogos'
      preLoaderRoute: typeof AuthenticatedPortalJogosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/api/public/sync-results': {
      id: '/api/public/sync-results'
      path: '/api/public/sync-results'
      fullPath: '/api/public/sync-results'
      preLoaderRoute: typeof ApiPublicSyncResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalJogosRoute: typeof AuthenticatedPortalJogosRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalJogosRoute: AuthenticatedPortalJogosRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalisesRoute: typeof AuthenticatedAnalisesRoute
  AuthenticatedArquivoRoute: typeof AuthenticatedArquivoRoute
  AuthenticatedCadastrarRoute: typeof AuthenticatedCadastrarRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCruzDoDiaRoute: typeof AuthenticatedCruzDoDiaRoute
  AuthenticatedEstatisticasRoute: typeof AuthenticatedEstatisticasRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedPalpiteRoute: typeof AuthenticatedPalpiteRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedRobotStatusRoute: typeof AuthenticatedRobotStatusRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalisesRoute: AuthenticatedAnalisesRoute,
  AuthenticatedArquivoRoute: AuthenticatedArquivoRoute,
  AuthenticatedCadastrarRoute: AuthenticatedCadastrarRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCruzDoDiaRoute: AuthenticatedCruzDoDiaRoute,
  AuthenticatedEstatisticasRoute: AuthenticatedEstatisticasRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedPalpiteRoute: AuthenticatedPalpiteRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedRobotStatusRoute: AuthenticatedRobotStatusRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PendenteRoute: PendenteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicSyncResultsRoute: ApiPublicSyncResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
